export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGOUT = 'LOGOUT';

export const LOCATION_REQUEST = 'LOCATION_REQUEST';
export const LOCATION_SUCCESS = 'LOCATION_SUCCESS';
export const LOCATION_FAILURE = 'LOCATION_FAILURE';

export const GET_LISTDATA_REQUEST = 'GET_LISTDATA_REQUEST';
export const GET_LISTDATA_SUCCESS = 'GET_LISTDATA_SUCCESS';
export const GET_LISTDATA_FAILURE = 'GET_LISTDATA_FAILURE';

export const SAVE_DATA_REQUEST = 'SAVE_DATA_REQUEST';
export const SAVE_DATA_SUCCESS = 'SAVE_DATA_SUCCESS';
export const SAVE_DATA_FAILURE = 'SAVE_DATA_FAILURE';

export const DELETE_DATA_REQUEST = 'DELETE_DATA_REQUEST';
export const DELETE_DATA_SUCCESS = 'DELETE_DATA_SUCCESS';
export const DELETE_DATA_FAILURE = 'DELETE_DATA_FAILURE';

export const GET_ITEMDATA_REQUEST = 'GET_ITEMDATA_REQUEST';
export const GET_ITEMDATA_SUCCESS = 'GET_ITEMDATA_SUCCESS';
export const GET_ITEMDATA_FAILURE = 'GET_ITEMDATA_FAILURE';

export const CREATE_POLYGON_REQUEST = 'CREATE_POLYGON_REQUEST';
export const CREATE_POLYGON_SUCCESS = 'CREATE_POLYGON_SUCCESS';
export const CREATE_POLYGON_FAILURE = 'CREATE_POLYGON_FAILURE';





















